In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-1.5.3-cp310-cp310-win_amd64.whl (10.4 MB)
     ---------------------------------------- 10.4/10.4 MB 2.6 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\asus\appdata\roaming\python\python310\site-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1
  Downloading pytz-2022.7.1-py2.py3-none-any.whl (499 kB)
     -------------------------------------- 499.4/499.4 kB 1.6 MB/s eta 0:00:00
Collecting numpy>=1.21.0
  Downloading numpy-1.24.2-cp310-cp310-win_amd64.whl (14.8 MB)
     ---------------------------------------- 14.8/14.8 MB 2.2 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Installing collected packages: pytz, numpy, pandas
Successfully installed numpy-1.24.2 pandas-1.5.3 pytz-2022.7.1

[notice] A new release of pip available: 22.2.2 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [17]:
df = pd.read_csv("./data.txt",sep=" |\t",expand=True)

TypeError: read_csv() got an unexpected keyword argument 'expand'

In [11]:
df

,0,1,2
0,ANAKING FAIQAL LUFI,NaN,1202223053 Bandung Basket
1,ALFONSUS RADITYA DAMAR YUDHISTIRA 1202223363 ...,NaN,NaN
2,ARIF LUKMAN HAKIM,NaN,1202223003 Bandung Sepak Bola
3,SALSABILA DIAH PUTRI ANDANY,NaN,1202223218 Bandung Menggambar
4,KAYLA PUTRI AURELIA,NaN,1202223006 Bandung Menyanyi
5,RAFFANDA FERGITA PUTERI,NaN,1202223292 Bandung Berenang
6,SYARIF IMAM MUSLIM,NaN,1202220108 Bandung Panahan
7,RAFIF DZAKY DANISWARA,NaN,1202223211 Bandung Basket
8,KRESNA MUKTI WIBOWO,NaN,1202223242 Bandung Mengoding
9,AIDA LIANA FEBIANSYAH,NaN,1202223078 Bandung Memasak
10,PANGERSO PANJI BIROWO,NaN,1202223087 Bandung Futsal
11,JAMES HESTU SATRIA,NaN,1202220127 Bandung Mengoding
12,LAVIO PUTERA ARYA SITANGGANG,1202220394 Bandung Basket,NaN
13,FARAH RAHIL NURIN SHABRINA,NaN,1202223191 Bandung Mendengarkan Lagu
14,HAFIZHAH FARAH FADHILA,NaN,1202220154 Bandung Melukis
15,MOCHAMMAD AZIIZ NUGROHO,NaN,1202223258 Bandung Sepak Bola
16,FERNANDO MANUEL,NaN,1202223288 Bandung Belajar
17,TIRZA DWI NINGRUM,NaN,1202223054 Bandung Memotret
18,BAGUS PRIAMBUDI,NaN,1202223036 Bandung Basket
19,INDAH FITRI AMELIA,NaN,1202223098 Bandung Menyanyi
20,IKHWAN AMIRUDDIN,NaN,1202223229 Bandung Jalan-jalan
21,ELSA TRIA LESTARI,NaN,1202220350 Bandung Dance
22,KEVIN HISHAM DEWANTO,NaN,1202223314 Bandung Berenang
23,AZHARA RAHMA EFFENDI,NaN,1202223254 Bandung Panahan
24,CERIA INDAH JELITA,NaN,1202223121 Bandung Melukis
25,KAYLA ZHAFIRA ARDINOV,NaN,1202223028 Bandung Dance
26,I KOMANG ANGGA CAHYA JULIASTANA,1202220068 Bandung Futsal,NaN
27,DUSTIN HARISYAHBAN BHINUKO,NaN,1202220148 Bandung Basket
28,PRADIPTA MUHTADIN,NaN,1202220327 Bandung Futsal
29,MUHAMAD REGA PRAMUDYA,NaN,1202223378 Bandung Basket
30,MUHAMMAD HAIDIR ALI AL-FARISIY,1202223165 Bandung Futsal,NaN
31,MUHAMMAD REYNAL FAWWAZ ABYASA,1202220272 Bandung Basket,NaN
32,MUHAMMAD GHINAN HAKIM,NaN,1202223020 Bandung Futsal
33,MUHAMMAD ATTHARIQ NUGERAHA 1202220194 ...,NaN,NaN

In [18]:
data = []

In [47]:
import re

coba = re.split(r"\s{2,}",data[2])
coba[0:4]
# cara ilangin spasi \t \n

['ARIF LUKMAN HAKIM', '1202223003', 'Bandung', 'Sepak Bola']

In [54]:
with open("data.txt","r") as file:
    read = file.readlines()
    data = []
    
    for line in read:
        temp = re.split(r"\s{2,}|\n",line)
        data.append(temp[0:4])
# ini baca file

In [100]:
df = pd.DataFrame(data, columns =['nama', 'nim', 'asal', 'hobi'])
df
# ini create tabel

                                 nama         nim     asal               hobi
0                 ANAKING FAIQAL LUFI  1202223053  Bandung             Basket
1   ALFONSUS RADITYA DAMAR YUDHISTIRA  1202223363  Bandung              Kasti
2                   ARIF LUKMAN HAKIM  1202223003  Bandung         Sepak Bola
3         SALSABILA DIAH PUTRI ANDANY  1202223218  Bandung         Menggambar
4                 KAYLA PUTRI AURELIA  1202223006  Bandung           Menyanyi
5             RAFFANDA FERGITA PUTERI  1202223292  Bandung           Berenang
6                  SYARIF IMAM MUSLIM  1202220108  Bandung            Panahan
7               RAFIF DZAKY DANISWARA  1202223211  Bandung             Basket
8                 KRESNA MUKTI WIBOWO  1202223242  Bandung          Mengoding
9               AIDA LIANA FEBIANSYAH  1202223078  Bandung            Memasak
10              PANGERSO PANJI BIROWO  1202223087  Bandung             Futsal
11                 JAMES HESTU SATRIA  1202220127  Bandung          Mengoding
12       LAVIO PUTERA ARYA SITANGGANG  1202220394  Bandung             Basket
13         FARAH RAHIL NURIN SHABRINA  1202223191  Bandung  Mendengarkan Lagu
14             HAFIZHAH FARAH FADHILA  1202220154  Bandung            Melukis
15            MOCHAMMAD AZIIZ NUGROHO  1202223258  Bandung         Sepak Bola
16                    FERNANDO MANUEL  1202223288  Bandung            Belajar
17                  TIRZA DWI NINGRUM  1202223054  Bandung           Memotret
18                    BAGUS PRIAMBUDI  1202223036  Bandung             Basket
19                 INDAH FITRI AMELIA  1202223098  Bandung           Menyanyi
20                   IKHWAN AMIRUDDIN  1202223229  Bandung        Jalan-jalan
21                  ELSA TRIA LESTARI  1202220350  Bandung              Dance
22               KEVIN HISHAM DEWANTO  1202223314  Bandung           Berenang
23               AZHARA RAHMA EFFENDI  1202223254  Bandung            Panahan
24                 CERIA INDAH JELITA  1202223121  Bandung            Melukis
25              KAYLA ZHAFIRA ARDINOV  1202223028  Bandung              Dance
26    I KOMANG ANGGA CAHYA JULIASTANA  1202220068  Bandung             Futsal
27         DUSTIN HARISYAHBAN BHINUKO  1202220148  Bandung             Basket
28                  PRADIPTA MUHTADIN  1202220327  Bandung             Futsal
29              MUHAMAD REGA PRAMUDYA  1202223378  Bandung             Basket
30     MUHAMMAD HAIDIR ALI AL-FARISIY  1202223165  Bandung             Futsal
31      MUHAMMAD REYNAL FAWWAZ ABYASA  1202220272  Bandung             Basket
32              MUHAMMAD GHINAN HAKIM  1202223020  Bandung             Futsal
33         MUHAMMAD ATTHARIQ NUGERAHA  1202220194  Bandung             Basket

In [59]:
df = df.append({'name':'', 'nim':'', 'asal':''}, ignore_index=True)
# ini insert

                                 nama         nim     asal               hobi
0                 ANAKING FAIQAL LUFI  1202223053  Bandung             Basket
1   ALFONSUS RADITYA DAMAR YUDHISTIRA  1202223363  Bandung              Kasti
2                   ARIF LUKMAN HAKIM  1202223003  Bandung         Sepak Bola
3         SALSABILA DIAH PUTRI ANDANY  1202223218  Bandung         Menggambar
4                 KAYLA PUTRI AURELIA  1202223006  Bandung           Menyanyi
5             RAFFANDA FERGITA PUTERI  1202223292  Bandung           Berenang
6                  SYARIF IMAM MUSLIM  1202220108  Bandung            Panahan
7               RAFIF DZAKY DANISWARA  1202223211  Bandung             Basket
8                 KRESNA MUKTI WIBOWO  1202223242  Bandung          Mengoding
9               AIDA LIANA FEBIANSYAH  1202223078  Bandung            Memasak
10              PANGERSO PANJI BIROWO  1202223087  Bandung             Futsal
11                 JAMES HESTU SATRIA  1202220127  Bandung          Mengoding
12       LAVIO PUTERA ARYA SITANGGANG  1202220394  Bandung             Basket
13         FARAH RAHIL NURIN SHABRINA  1202223191  Bandung  Mendengarkan Lagu
14             HAFIZHAH FARAH FADHILA  1202220154  Bandung            Melukis
15            MOCHAMMAD AZIIZ NUGROHO  1202223258  Bandung         Sepak Bola
16                    FERNANDO MANUEL  1202223288  Bandung            Belajar
17                  TIRZA DWI NINGRUM  1202223054  Bandung           Memotret
18                    BAGUS PRIAMBUDI  1202223036  Bandung             Basket
19                 INDAH FITRI AMELIA  1202223098  Bandung           Menyanyi
20                   IKHWAN AMIRUDDIN  1202223229  Bandung        Jalan-jalan
21                  ELSA TRIA LESTARI  1202220350  Bandung              Dance
22               KEVIN HISHAM DEWANTO  1202223314  Bandung           Berenang
23               AZHARA RAHMA EFFENDI  1202223254  Bandung            Panahan
24                 CERIA INDAH JELITA  1202223121  Bandung            Melukis
25              KAYLA ZHAFIRA ARDINOV  1202223028  Bandung              Dance
26    I KOMANG ANGGA CAHYA JULIASTANA  1202220068  Bandung             Futsal
27         DUSTIN HARISYAHBAN BHINUKO  1202220148  Bandung             Basket
28                  PRADIPTA MUHTADIN  1202220327  Bandung             Futsal
29              MUHAMAD REGA PRAMUDYA  1202223378  Bandung             Basket
30     MUHAMMAD HAIDIR ALI AL-FARISIY  1202223165  Bandung             Futsal
31      MUHAMMAD REYNAL FAWWAZ ABYASA  1202220272  Bandung             Basket
32              MUHAMMAD GHINAN HAKIM  1202223020  Bandung             Futsal
33         MUHAMMAD ATTHARIQ NUGERAHA  1202220194  Bandung             Basket
34                                             25
35

In [60]:
search_by = "nama" 
value = ""
index = df[df[search_by].str.lower().str.contains(value)].index
# ini search

   nama nim asal hobi
34       25
35

In [61]:
df.drop(index, inplace=True)
# ini delete

In [104]:

df.loc[index,["nama"]] = ["FARAH RAHIL NURIN SHABRINA"]
# update

In [115]:
with open('dataex.txt', 'w') as f: df.to_string(f, col_space=10, header=False, index=False)
# save to file

In [ ]:
def read_data(filename:str) -> list:
    return []

In [ ]:
def create_table(data:list) -> pd.DataFrame:
    return pd.DataFrame()

In [ ]:
def get_data(search):
    pass

In [ ]:
def insert_data(data:list):
    pass

In [ ]:
def update_data(search):
    pass

In [ ]:
def delete_data(search):
    pass

In [ ]:
def save_data(table:pd.DataFrame):
    pass